paths:
    /api/products/:
        get:
            summary: obtiene todos los productos
            tags:
                - Products
            responses:
                "200":
                    description: los productos fueron obtenidos correctamente
                    content:
                        application/json:
                            schema:
                                type: array
                                items:
                                    $ref: "#components/schemas/Product"
                "500":
                    description: error interno de server, usualmente generado por una query defectuosa
        post:
            summary: Creacion de producto
            tags:
                - Products
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: "#components/requestBodies/updateProduct"
            responses:
                "200":
                    description: el producto se creo de forma correcta.
                "404":
                    description: error al crear el producto.
                "500":
                    description: error interno de server, usualmente generado por una query defectuosa
    /api/products/{pid}:
        get:
            summary: obtiene un producto por su pid
            tags:
                - Products
            parameters:
                - name: pid
                  in: path
                  required: true
                  description: el id del producto a solicitar.
                  schema:
                      $type: String
            responses:
                "200":
                    description: el producto fue obtenido correctamente
                    content:
                        application/json:
                            schema:
                                $ref: "#components/schemas/Product"
                "404":
                    description: Producto pasado por pid no encontrado.
                "500":
                    description: error interno de server, usualmente generado por una query defectuosa
        put:
            summary: Se actualiza un producto por su pid
            tags:
                - Products
            parameters:
                - name: pid
                  in: path
                  required: true
                  description: El product id del producto a actualizar.
                  schema:
                      $type: String
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: "#components/requestBodies/updateProduct"
            responses:
                "200":
                    description: el producto fue actualizado correctamente
                    content:
                        application/json:
                            schema:
                                $ref: "#components/schemas/Product"
                "401":
                    description: No esta Logeado o su usuario no tiene permisos para hacer esta accion.
                "404":
                    description: No existe el producto pasado por pid. El producto pasado por pid para modificar no pertenece al usuario logeado.
                "500":
                    description: error interno de server, usualmente generado por una query defectuosa
        delete:
            summary: Se Borra un producto por su pid
            tags:
                - Products
            parameters:
                - name: pid
                  in: path
                  required: true
                  description: El product id del producto a borrar.
                  schema:
                      $type: String
            responses:
                "200":
                    description: el producto fue borrado correctamente
                    content:
                        application/json:
                            schema:
                                $ref: "#components/schemas/Product"
                "401":
                    description: No esta Logeado o su usuario no tiene permisos para hacer esta accion.
                "404":
                    description: No existe el producto pasado por pid. El producto pasado por pid para borrar no pertenece al usuario logeado.
                "500":
                    description: error interno de server, usualmente generado por una query defectuosa
components:
    schemas:
        Product:
            type: object
            properties:
                _id:
                    type: string
                    description: Id autogenerado por Mongo.
                name:
                    type: string
                    description: Nombre del producto.
                description:
                    type: string
                    description: Descripcion del producto.
                price:
                    type: number
                    description: precio del producto.
                image:
                    type: array
                    items:
                        type: string
                        description: imagen del producto
                code:
                    type: string
                    description: codigo del producto.
                category:
                    type: string
                    description: categoria del producto.
                status:
                    type: boolean
                    description: estado del producto.
                stock:
                    type: number
                    description: stock del producto.
                owner:
                    type: string
                    description: email del creador del producto.
            example:
                _id: ObjectId("fafafa213fafa")
                category: "nike"
                name: "AIR JORDAN 1 LOW ROYAL YELLOW"
                price: 74799
                image: "https://raw.githubusercontent.com/cessarmartinez/DesafioJS/main/assets/img/lowroyalyellow.png"
                stock: 56
                code: 253
                description: "zapatilla air jordan 1 low royal yellow"
    requestBodies:
        updateProduct:
            type: object
            properties:
                name:
                    type: string
                    description: Titulo del producto.
                description:
                    type: string
                    description: Descripcion del producto.
                price:
                    type: number
                    description: precio del producto.
                image:
                    type: array
                    items:
                        type: string
                        description: imagen del producto
                code:
                    type: string
                    description: codigo del producto.
                category:
                    type: string
                    description: categoria del producto.
                status:
                    type: boolean
                    description: estado del producto.
                stock:
                    type: number
                    description: stock del producto.
                owner:
                    type: string
                    description: email del creador del producto.
            example:
                category: "nike"
                name: "AIR JORDAN 1 LOW ROYAL YELLOW"
                price: 74799
                image: "https://raw.githubusercontent.com/cessarmartinez/DesafioJS/main/assets/img/lowroyalyellow.png"
                stock: 56
                code: 253
                status: true
                description: "zapatilla air jordan 1 low royal yellow"
                owner: usuario@gmail.com
